version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: caixa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Nil0n1.12
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: ./caixa
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/caixa
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Nil0n1.12
    ports:
      - "8080:8080"
    volumes:
      - ./caixa:/app

volumes:
  db_data: